package view;

import javax.swing.table.DefaultTableModel;
import model.Actualizar_tabla;
import model.Lista_Productos;

/**

 @author sebas
 */
public class EstacionDeCarga extends javax.swing.JFrame {

    public DefaultTableModel dtm_product;
    
    /** Creates new form EstacionDeCarga */
    public EstacionDeCarga() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Estación de Carga");
        table_products();
        
                
        Actualizar_tabla tabla = new Actualizar_tabla();
        tabla.agregar_productos(dtm_product, Lista_Productos.productos);
    }
    
    public void table_products(){
        dtm_product = new DefaultTableModel(); //Se inicializa el dtm_muestras
        String id[] = {"Código", "Nombre", "Material", "Color"};
        dtm_product.setColumnIdentifiers(id); //Se agrega el vector id al encabezado del dtm_muestras
        table_products.setModel(dtm_product); //A la tabla muestras se le asigna el modelo que se definió arriba
    }

    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        label_title = new javax.swing.JLabel();
        btn_load = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_products = new javax.swing.JTable();
        btn_produce = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_title.setText("ESTACIÓN DE CARGA");

        btn_load.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_load.setText("CARGAR PRODUCTOS");

        table_products = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        table_products.setModel(new javax.swing.table.DefaultTableModel(

        ));
        jScrollPane1.setViewportView(table_products);

        btn_produce.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_produce.setText("PRODUCIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_load))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_title)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_produce)
                        .addGap(372, 372, 372))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(label_title)
                .addGap(48, 48, 48)
                .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btn_produce)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_load;
    public javax.swing.JButton btn_produce;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel label_title;
    public javax.swing.JTable table_products;
    // End of variables declaration//GEN-END:variables
}
