package view;

/**

 @author sebas
 */
public class Producir extends javax.swing.JFrame {

    /** Creates new form Producir */
    public Producir() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Producir");
    }

    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_cod = new javax.swing.JLabel();
        label_cantidad = new javax.swing.JLabel();
        btn_produce = new javax.swing.JButton();
        field_cod = new javax.swing.JTextField();
        field_cantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_cod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_cod.setText("Código:");

        label_cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_cantidad.setText("Cantidad:");

        btn_produce.setText("PRODUCIR");
        btn_produce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_cod)
                            .addComponent(label_cantidad))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_cod)
                            .addComponent(field_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btn_produce)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cod)
                    .addComponent(field_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cantidad)
                    .addComponent(field_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btn_produce)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_produceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_produceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_produce;
    public javax.swing.JTextField field_cantidad;
    public javax.swing.JTextField field_cod;
    public javax.swing.JLabel label_cantidad;
    public javax.swing.JLabel label_cod;
    // End of variables declaration//GEN-END:variables
}
